### PR TITLE
update setup to include the requirements

### PR DESCRIPTION
**Pull request by davguez**
fix for this [issue](https://github.com/mitmedialab/date_guesser/issues/3#issue-377175505)
directly include the requirements to the setup file

### CODE REVIEW

**Comment by pypt** [comment]
Oh, here it is!

Would you be able to:

1) Remove `requirements.txt` (as you did in https://github.com/mitmedialab/date_guesser/pull/5),
2) Add requirements to `setup.py` (as you did in this PR), and
3) Indent the `install_requires` array more nicely?

To amend this pull request, just add some more commits to your `patch-1` branch and do `git push`.

**Comment by ColCarroll** [comment]
Thanks @davguez!

@pypt any objection to just merging this and #5, then I can cut a release? I am not a maintainer of this github repo, but can release on pypi.

**Comment by pypt** [comment]
Sure, go ahead. Thanks Colin & David!

**Comment by ColCarroll** [comment]
Er, sorry for not being clear - I don't have write access to this repo, so you would have to merge.

**Comment by pypt** [comment]
Closing as https://github.com/mitmedialab/date_guesser/pull/6 has been merged instead.

**Comment by pypt** [comment]
@ColCarroll, would you be able to release an updated version (I've bumped a version number and tagged it as `2.1.2`), or add me to a list of `date_guesser`'s collaborators on PyPI?

**Pull request closed without merging**
